train_8 = [
    # left, top, width, height, xofs, yofs
	[   25,   2,     8,     23,   -3,  -11],  # n
	[   35,   2,    21,     18,  -11,  -11],  # ne
	[   58,   2,    32,     12,  -16,   -7],  # e
	[   92,   2,    21,     18,  -12,  -12],  # se
	[  115,   2,     8,     23,   -3,  -11],  # s
	[  125,   2,    21,     18,  -11,  -11],  # sw
	[  148,   2,    32,     12,  -16,   -7],  # w
	[  182,   2,    21,     18,  -12,  -12],  # nw
]

train20px = [
    # left_x, upper_y, width, height, offset_x, offset_y
    [0, 0, 8, 18, -3, -11],
    [9, 0, 15, 15, -7, -10],
    [25, 0, 20, 12, -4, -8],
    [46, 0, 15, 15, 1, -7],
    [62, 0, 8, 17, -3, -5],
    [71, 0, 15, 15, -13, -7],
    [87, 0, 20, 12, -16, -8],
    [108, 0, 15, 15, -5, -10],
]

# THIS VIEW IS 8 FROM 4, IT REPEATS THE SECOND SET FOR OFFSET PURPOSES
train20px_4view = [ # Clone to 8view when changed
    # left_x, upper_y, width, height, offset_x, offset_y
    [0, 0, 8, 18, -3, -11],
    [9, 0, 15, 15, -7, -10],
    [25, 0, 20, 12, -4, -8],
    [46, 0, 15, 15, 1, -7],
    [0, 0, 8, 17, -3, -5],
    [9, 0, 15, 15, -13, -7],
    [25, 0, 20, 12, -16, -8],
    [46, 0, 15, 15, -5, -10],
]

train20px_anim = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO ANIM
    [0, 0, 8, 17, -4, -11],
    [10, 0, 15, 15, -7, -10],
    [27, 0, 20, 12, -4, -8],
    [49, 0, 15, 15, -1, -8],
    [66, 0, 8, 17, -4, -3],
    [76, 0, 15, 15, -14, -7],
    [93, 0, 20, 12, -16, -8],
    [115, 0, 15, 15, -7, -11],
]

train24px = [
    # left_x, upper_y, width, height, offset_x, offset_y
    [0, 0, 8, 20, -3, -11],
    [9, 0, 17, 16, -9, -10],
    [27, 0, 24, 12, -8, -8],
    [52, 0, 17, 16, -1, -8],
    [70, 0, 8, 20, -3, -7],
    [79, 0, 17, 16, -13, -8],
    [97, 0, 24, 12, -16, -8],
    [122, 0, 17, 16, -5, -10],
]

train28px_pacer = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM
    [0, 0, 8, 19, -3, -9],
    [9, 0, 19, 15, -11, -9],
    [29, 0, 28, 12, -7, -7],
    [58, 0, 19, 15, -5, -8],
    [78, 0, 8, 19, -3, -9],
    [87, 0, 19, 15, -15, -6],
    [107, 0, 28, 12, -17, -6],
    [136, 0, 19, 15, -8, -9],
]

train28px = [
    # left_x, upper_y, width, height, offset_x, offset_y
    [0, 0, 8, 22, -3, -11],
    [9, 0, 19, 17, -11, -10],
    [29, 0, 28, 12, -12, -8],
    [58, 0, 19, 17, -3, -9],
    [78, 0, 8, 22, -3, -9],
    [87, 0, 19, 17, -13, -9],
    [107, 0, 28, 12, -16, -8],
    [136, 0, 19, 17, -5, -10],
]

train32px = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM
    [0, 0, 8, 24, -3, -12],
    [9, 0, 21, 18, -13, -10],
    [31, 0, 32, 12, -16, -8],
    [64, 0, 21, 18, -5, -10],
    [86, 0, 8, 24, -3, -12],
    [95, 0, 21, 18, -13, -10],
    [117, 0, 32, 12, -16, -8],
    [150, 0, 21, 18, -5, -10],
]

train32px_anim = [
    # left_x, upper_y, width, height, offset_x, offset_y
    #TODO ANIM|NOWHITE
    [0, 0, 8, 24, -4, -10],
    [9, 0, 21, 18, -13, -10],
    [31, 0, 32, 12, -16, -8],
    [64, 0, 21, 18, -7, -11],
    [86, 0, 8, 24, -4, -10],
    [95, 0, 21, 18, -13, -10],
    [117, 0, 32, 12, -16, -8],
    [150, 0, 21, 18, -7, -11],
]

# TODO lowercase?
train32px4viewLowered = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM|NOWHITE
    [0, 0, 8, 24, -3, -12],
    [9, 0, 21, 17, -12, -8],
    [31, 0, 32, 12, -16, -7],
    [64, 0, 21, 17, -5, -8],
]

train32px_reversed = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM|NOWHITE
    [86, 0, 8, 24, -3, -12],
    [95, 0, 21, 17, -12, -10],
    [117, 0, 32, 12, -16, -8],
    [150, 0, 21, 17, -5, -10],
	[0, 0, 8, 24, -3, -12],
    [9, 0, 21, 17, -12, -10],
    [31, 0, 32, 12, -16, -8],
    [64, 0, 21, 17, -5, -10],
]

# TODO lowercase?
trainBRMk2 = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM|NOWHITE
    [0, 0, 8, 24, -3, -12],
    [9, 0, 21, 17, -11, -10],
    [31, 0, 32, 12, -11, -7],
    [64, 0, 21, 17, -9, -9],
    [86, 0, 8, 24, -3, -12],
    [95, 0, 21, 17, -15, -6],
    [117, 0, 32, 12, -11, -6],
    [150, 0, 21, 17, -9, -9],
]

template_450 = [
    # left_x, upper_y, width, height, offset_x, offset_y
    [0, 0, 8, 26, -3, -9],
    [9, 0, 22, 21, -16, -10],
    [32, 0, 32, 13, -15, -7],
    [65, 0, 22, 21, -1, -10],
    [88, 0, 8, 26, -3, -11],
    [97, 0, 22, 21, -16, -10],
    [120, 0, 32, 13, -13, -7],
    [153, 0, 22, 21, -3, -10],
]

train170pt = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM|NOWHITE
    [0, 0, 8, 26, -3, -9],
    [9, 0, 22, 21, -16, -12],
    [32, 0, 32, 12, -15, -7],
    [65, 0, 22, 21, -4, -11],
    [88, 0, 8, 26, -3, -11],
    [97, 0, 22, 21, -15, -12],
    [120, 0, 32, 12, -13, -7],
    [153, 0, 22, 21, -4, -11],
]

# Now only used by MPV
train170ptF = [
    # left_x, upper_y, width, height, offset_x, offset_y
    # TODO NOANIM|NOWHITE
    [0, 0, 8, 26, -3, -9],
    [9, 0, 22, 21, -16, -12],
    [32, 0, 32, 12, -13, -7],
    [65, 0, 22, 21, -4, -11],
    [88, 0, 8, 26, -3, -11],
    [97, 0, 22, 21, -15, -12],
    [120, 0, 32, 12, -15, -7],
    [153, 0, 22, 21, -4, -11],
]

train70pt = [
    # left_x, upper_y, width, height, offset_x, offset_y
    [0, 0, 8, 25, -3, -9],
    [9, 0, 22, 20, -16, -12],
    [32, 0, 32, 12, -15, -7],
    [65, 0, 22, 20, -4, -11],
    [88, 0, 8, 25, -3, -11],
    [97, 0, 22, 20, -15, -12],
    [120, 0, 32, 12, -13, -7],
    [153, 0, 22, 20, -4, -11],
]


# Only used by MPV
purchaseptdual = [
    # left_x, upper_y, width, height, offset_x, offset_y
    [],
    [],
    [32, 0, 32, 12, -13, -7],
    [],
    [],
    [],
    [120, 0, 32, 12, -11, -7],
    [],
]

purchase = [
    # xpos, ypos,   width,  height, xoffset, yoffset
    # TODO NOANIM|NOWHITE
    [    0,    0,      87,      12,     -25,      -6]
]


purchase_anim = [
    # xpos, ypos,   width,  height, xoffset, yoffset
    # TODO ANIM|NOWHITE
    [    0,    0,      87,      12,     -25,      -6]
]
